### ISSUE TITLE
There are problems with reproducing the results in the paper.

### ISSUE THREAD

**Issue by ZechCal** [jiaxiaojunQAQ/FGSM-LAW#1]
Running the CIFAR-10 experiment of LAW directly yields accuracy results of 80.93/55.96/54.95/47.53 for Clean/PGD-20/PGD-50/AA, which do not match the paper’s reported values of 81.36//56.36/49.22. 

Additionally, the algorithm encountered catastrophic failure on the WRN3410 model, achieving only 51/37 accuracy. Could it be that the parameters for the WRN3410 model are not consistent with those for ResNet18?

**Comment by jiaxiaojunQAQ** [comment]
> Running the CIFAR-10 experiment of LAW directly yields accuracy results of 80.93/55.96/54.95/47.53 for Clean/PGD-20/PGD-50/AA, which do not match the paper’s reported values of 81.36//56.36/49.22.
> 
> Additionally, the algorithm encountered catastrophic failure on the WRN3410 model, achieving only 51/37 accuracy. Could it be that the parameters for the WRN3410 model are not consistent with those for ResNet18?

Thanks for your attention to our work. The hyperparameters in the original file are not optimal. I have made some corrections. The hyperparameters of WRN are inconsistent with ResNet18. Since this work was completed during my internship at Alibaba Group, and I have left the company now, I need to visit the machine there to set some parameters. Generally, the value of EMA_value should be lowered. Or wait for me to reproduce this result.

**Comment by ZechCal** [comment]
Thank you very much for your kindly response! Looking forward to seeing the next update :)

**Comment by jiaxiaojunQAQ** [comment]
> Thank you very much for your kindly response! Looking forward to seeing the next update :)

I have updated it and verified the results on CIFAR10, and the results are consistent with those reported in the paper.
